### ISSUE TITLE
Lösning på array-övning 4 ger fel svar

### ISSUE THREAD

**Issue by spacecakes** [fend17/cms-php-mysql#1]
Instruktionerna säger att man ska multiplicera integers i arrayen,  `1 * 2 * 3 * 4 * 5 = 120`, men lösningsförslaget adderar dem, vilket ger `15`. 

Lite klurigt att lösa eftersom att starta `$sum ` på `0` innebär att det första varvet i loopen skulle bli `0` istället för `1`. Men typ så här:

```
$best_array = array(1, 2, 3, 4, 5);
$sum = $best_array[0];

for ($i = 0; $i < count($best_array); $i++) {
    $sum = $sum * $best_array[$i];
}
echo "<p>$sum</p>";
```

**Comment by jesperorb** [comment]
Skämmigt av mig, uppdaterat nu enligt denna lösning, tack!

Bra att använda dig utav issues!
